version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
